spring:
  application:
    name: board-with-vue-spring
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  datasource:
#    username: root
#    password:
#    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/board?serverTimezone=UTC&characterEncoding=UTF-8

logging:
  level:
    web: debug